export interface AnalysisResult {
    summary: string;
    sentiment: 'positive' | 'negative' | 'neutral';
    keyTakeaways: string[];
}

const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent';

export async function generateEarningsAnalysis(text: string, symbol: string): Promise<AnalysisResult> {
    const apiKey = process.env.GOOGLE_AI_API_KEY;

    if (!apiKey) {
        throw new Error('GOOGLE_AI_API_KEY is not configured');
    }

    const prompt = `
    Analyze the following earnings report text for ${symbol}. 
    Provide a structured summary with:
    1. A concise paragraph summarizing the key financial results (Revenue, EPS, comparison to guidance/estimates).
    2. A sentiment assessment (Positive, Negative, Neutral).
    3. Three key takeaways or highlights (bullet points).
    
    Text:
    ${text.substring(0, 30000)} // Truncate to avoid context limits if text is huge
  `;

    // JSON schema for structured output isn't strictly enforced by Flash via REST without config, 
    // but we can ask for JSON or specific format. For robustness, let's ask for JSON.
    // Actually, for simplicity in this demo, let's just ask for text and parse loosely or return text.
    // "You can use a model to parse... and show a summary".
    // Let's try to get a JSON response for better UI integration.

    const payload = {
        contents: [{
            parts: [{
                text: prompt + "\n\nResponse format: JSON with keys 'summary', 'sentiment', 'keyTakeaways' (array of strings)."
            }]
        }],
        generationConfig: {
            temperature: 0.2,
            responseMimeType: "application/json"
        }
    };

    try {
        const response = await fetch(`${GEMINI_API_URL}?key=${apiKey}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`Gemini API Error: ${response.status} - ${errorText}`);
        }

        const data = await response.json();
        const resultText = data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!resultText) {
            throw new Error('No content generated by Gemini');
        }

        return JSON.parse(resultText) as AnalysisResult;
    } catch (error) {
        console.error('Gemini Analysis Failed:', error);
        // Fallback or rethrow
        throw error;
    }
}
